### ISSUE TITLE
Dragon freezer roadmap

### ISSUE THREAD

**Issue by ErnWong** [ErnWong/dotfiles-old-divnix#35]
Meta:

- [ ] Generate documentation: https://gitlab.com/rycee/nmd

Features to support:

TODO: Go through each setting in System Settings, and change each setting, using git to figure out the appropriate rc file change, and implement it, and document the relationship between System Settings and the nix config.
TODO: Reorganize by how System Settings groups things.

- [ ] Mouse kcminputrc
    - [x] Cursor theme
    - [x] Cursor size https://github.com/ErnWong/dotfiles/commit/0dbe2dc91a3e2160f2895e64892f3a88359a9f27
    - [ ] Acceleration
    - [ ] Threshold
    - [ ] Mouse button mapping
    - [ ] Reverse scroll polarity
- [ ] ksplashrc 
- [ ] kdeglobals
    - [ ] kdeglobals.KDE.widgetStyle Widget style (breeze, kvantum)
    - [ ] kdeglobals.KDE.LookandFeelPackage Look and feel (org.kde.plasma.phone)
    - [ ] kdeglobals.General.ColorScheme Color scheme (Numix)
    - [ ] kdeglobals.Icons.Theme Icon theme (Numix-Circle, Ant-Dark)
    - [ ] kdeglobals_kscreen_scalefactor
    - [ ] kdeglobals_kscreen_screenscalefactors
- [ ] kcmfonts
    - [ ] kcmfonts_general_forcefontdpi
- [ ] Plasma theme
- [ ] Window
    - [ ] Kdecoration2 (window decorations)
    - [ ] Placement (maximizing)
    - [ ] Desktops (number, rows)
- [ ] Dolphin
    - [ ] Menu bar disabled
- [ ] Plasma desktop applets
    - [ ] Contaiments, panels, system tray, folder
- [ ] Keyboard shortcuts
- [ ] Keyboard global hotkeys

Reorganised:

- [ ] Appearance
    - [ ] Global Theme (Breeze, Breeze Dark, Breeze Twilight, Oxygen. Why are each Breeze theme duplicated?). This seems to be about everything combined.
        - [ ] Use desktop layout from theme (Boolean)
    - [ ] Application Style (Breeze, Fusion, MS Windows 9x (hell yes, maybe I should use this one), Oxygen). This seems to be about the look and feel? The Qt "skin" for each controls (e.g. tabs, check boxes, buttons, scroll bars) https://github.com/KDE/plasma-workspace/blob/c6a46adf16aa1f3debf83d96214a3f33316c9cf5/kcms/style/package/contents/ui/main.qml
        - [ ] Configure Icons and Toolbars
            - [ ] Show icons -> on buttons (Boolean, default to True)
            - [ ] Show icons -> in menus (Boolean, default to True)
            - [ ] Main toolbar label: (None, Text only, Beside icons, Below icon, default to Besides icons)
            - [ ] Secondary toolbar label: (None, Text only, Beside icons, Below icon, default to Besides icons)
    - [ ] Plasma Style  (Air, Breeze, Breeze Dark, Breeze Light, Oxygen). This seems to be about panel and widget appearances.  https://github.com/KDE/plasma-workspace/blob/c6a46adf16aa1f3debf83d96214a3f33316c9cf5/kcms/desktoptheme/package/contents/ui/main.qml
    - [ ] Colors (Breeze, Breeze Dark, Breeze High Contrast, Breeze Light, Oxygen, Oxygen Cold)
        - [ ] Use accent color: (From current color scheme, Custom (8 choices))
    - [ ] Window decorations todo
        - [ ] Theme todo
            - [ ] Window border size todo 
        - [ ] Titlebar Buttons todo
            - [ ] Close windows by double clicking the menu button todo
            - [ ] Show titlebar button tooltips todo
    - [ ] todo
- [ ] Workspace
- [ ] Personalization
- [ ] Network
- [ ] Hardware
- [ ] System Administration

Resources:

https://github.com/shalva97/kde-configuration-files/blob/14455771c68914682ac4cc281e2e790013d26fb8/README.md
https://pclosmag.com/html/Issues/201707/page14.html
https://github.com/AsterisMono/flake/blob/47a933674509b5657032930652fdc848468b5ffb/configurations/modules/gui/plasma/default.nix
https://api.kde.org/frameworks/kconfig/html/options.html

https://develop.kde.org/deploy/kiosk/introduction/

> Appending [$i] to the configuration key marks it as immutable. As configuration files from $XDG_CONFIG_DIRS are read before $XDG_CONFIG_HOME, the background is now “locked down” and any custom settings made by a user to it, either directly or though a configuration dialog, will not be read by the configuration system.

The pages in System Settings are supplied via KDE Configuration Modules:
https://develop.kde.org/docs/extend/kcm/

This talks about where Plasma Style comes from: /usr/share/plasma/desktoptheme (https://invent.kde.org/frameworks/plasma-framework/-/tree/master/src/desktoptheme) and ~/.local/share/plasma/desktoptheme/ https://store.kde.org/browse?cat=104&ord=latest and many more (Color Theme, Icon Theme, Task Switcher, Plasma Widget, Panel Layout Template...)
https://github.com/KDE/documentation-develop-kde-org/blob/038df6ca70908bc732c62ec582034d6d900a31ce/content/docs/plasma/_index.md
